-- Sanitized example for public documentation.
-- This is not a production deployment script.

CREATE TABLE ai_alertas (
  id_alerta            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  no_cia               VARCHAR2(10),
  centro               NUMBER,
  modulo               VARCHAR2(50) NOT NULL,
  tipo_alerta          VARCHAR2(100) NOT NULL,
  referencia_tipo      VARCHAR2(100),
  referencia_id        VARCHAR2(100),
  clave_dedup          VARCHAR2(300),
  severidad            VARCHAR2(20),
  estado               VARCHAR2(30) DEFAULT 'PENDIENTE_IA' NOT NULL,
  datos_json           CLOB CHECK (datos_json IS JSON),
  titulo               VARCHAR2(200),
  mensaje              VARCHAR2(1000),
  accion_sugerida      VARCHAR2(1000),
  usuario_destino      VARCHAR2(100),
  rol_destino          VARCHAR2(100),
  app_id               NUMBER,
  page_id              NUMBER,
  url_redireccion      VARCHAR2(1000),
  modelo_ia            VARCHAR2(100),
  intentos_ia          NUMBER DEFAULT 0 NOT NULL,
  ultimo_error_ia      VARCHAR2(1000),
  fecha_detectada      DATE DEFAULT SYSDATE NOT NULL,
  fecha_ultimo_intento DATE,
  fecha_generada_ia    DATE,
  fecha_atendida       DATE,
  creado_por           VARCHAR2(100) DEFAULT USER NOT NULL,
  creado_el            DATE DEFAULT SYSDATE NOT NULL,
  actualizado_el       DATE
);

CREATE UNIQUE INDEX ai_alertas_u01
  ON ai_alertas (no_cia, clave_dedup);

CREATE INDEX ai_alertas_i01
  ON ai_alertas (estado, fecha_detectada);

CREATE INDEX ai_alertas_i02
  ON ai_alertas (no_cia, centro, usuario_destino, estado, fecha_detectada);

COMMENT ON TABLE ai_alertas IS
  'Queue and cache of AI-assisted operational suggestions for Oracle APEX dashboards.';

